### ISSUE TITLE
Consider not showing alert about configuration load on login

### ISSUE THREAD

**Issue by kasper** [jasonm23/phoenix#18]
Consider not showing alert about configuration load on login. In my opinion, alerts on configuration file changes and reloads would suffice.

**Comment by kasper** [comment]
@jasonm23 Great, thanks for maintaining this awesome project!

**Comment by jasonm23** [comment]
Hey @kasper I got sick in Thailand, so didn't have a good opportunity to get this done.  I'll have a look asap.

**Comment by kasper** [comment]
@jasonm23 I created a pull-request.
