### ISSUE TITLE
Alerts are displayed off-screen in a multi-display setup

### ISSUE THREAD

**Issue by kasper** [jasonm23/phoenix#19]
Alerts are displayed off-screen in a multi-display setup. With two screens, they display on the “edge” of the screens and are cut off.

**Comment by jasonm23** [comment]
I have yet to test this. flag to myself todo soon.

**Comment by jasonm23** [comment]
Tested, working ok for a two screen setup, `api.alert` is shows in the primary display. 

Tested on MPB13 with external screen, and iMac with external screen.

![Uploading Screen Shot 2015-01-09 at 6.42.57 pm.png . . .]()
![Uploading Screen Shot 2015-01-09 at 6.42.57 pm (2).png . . .]()

**Comment by kasper** [comment]
Weird, definitely not working for me. MBP 13" and 27" external display. Could the display arrangement have an effect?

![display-arrangement](https://cloud.githubusercontent.com/assets/925851/5678830/591d807c-97ff-11e4-8398-65463cc313c7.png)

**Comment by jasonm23** [comment]
I suppose it could be Yosemite- I'm still on ML and will not be joining the Yosemite "party" until Q3 2015

**Comment by kasper** [comment]
Yep, I think this is caused by changes in Yosemite.
